version: '3'
services:
  app: 
    build:
      context: .
    ports:
      - "127.0.0.1:8080:3000"
    volumes:
      - ".:/app"
    command: >
      sh -c "yarn install &&
             yarn build &&
             yarn serve"