services:
  catalog: 
    build:
      context: .
    ports:
      - "127.0.0.1:8030:3000"
    volumes:
      - ".:/catalog"
    command: >
      sh -c "yarn install &&
             yarn build &&
             yarn serve"
# networks:
#   default:
#     external: true
#     name: postgres_network  