version: '3'
services:
  app: 
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    command: >
      sh -c "yarn install &&
             yarn build &&
             yarn serve"

             version: "3.9"   